In [3]:
import pandas as pd
import numpy as np

In [23]:
X = pd.DataFrame(data=np.ones((10, 1)), index=range(10))
y = pd.DataFrame(data=np.hstack(([0] * 7, [1] * 3)), index=range(10))

## K-折交叉验证

In [ ]:
from sklearn.model_selection import KFold

In [26]:
kf = KFold(n_splits=5, random_state=42)
splits = kf.split(X)
for train_idx, test_idx in splits:
    print(train_idx, test_idx)

[2 3 4 5 6 7 8 9] [0 1]
[0 1 4 5 6 7 8 9] [2 3]
[0 1 2 3 6 7 8 9] [4 5]
[0 1 2 3 4 5 8 9] [6 7]
[0 1 2 3 4 5 6 7] [8 9]


### Shuffling

In [42]:
kf = KFold(n_splits=5, shuffle=True)
splits = kf.split(X)
for train_idx, test_idx in splits:
    print(train_idx, test_idx)

[0 1 2 4 5 6 7 8] [3 9]
[0 1 3 4 5 6 8 9] [2 7]
[0 1 2 3 4 5 7 9] [6 8]
[0 1 2 3 6 7 8 9] [4 5]
[2 3 4 5 6 7 8 9] [0 1]


## 留一交叉验证（LOOC）

In [43]:
from sklearn.model_selection import LeaveOneOut

In [45]:
loo = LeaveOneOut()
splits = loo.split(X)
for train_idx, test_idx in splits:
    print(train_idx, test_idx)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


In [46]:
kf = KFold(n_splits=10, random_state=42)
splits = kf.split(X)
for train_idx, test_idx in splits:
    print(train_idx, test_idx)

[1 2 3 4 5 6 7 8 9] [0]
[0 2 3 4 5 6 7 8 9] [1]
[0 1 3 4 5 6 7 8 9] [2]
[0 1 2 4 5 6 7 8 9] [3]
[0 1 2 3 5 6 7 8 9] [4]
[0 1 2 3 4 6 7 8 9] [5]
[0 1 2 3 4 5 7 8 9] [6]
[0 1 2 3 4 5 6 8 9] [7]
[0 1 2 3 4 5 6 7 9] [8]
[0 1 2 3 4 5 6 7 8] [9]


## 随机置换交叉验证

In [31]:
from sklearn.model_selection import ShuffleSplit

In [32]:
ss = ShuffleSplit(n_splits=5, test_size=0.25, random_state=0)
for train_idx, test_idx in ss.split(X):
    print(train_idx, test_idx)

[9 1 6 7 3 0 5] [2 8 4]
[2 9 8 0 6 7 4] [3 5 1]
[4 5 1 0 6 9 7] [2 3 8]
[2 7 5 8 0 3 4] [6 1 9]
[4 1 0 6 8 9 3] [5 2 7]
